apiVersion: v1
kind: Pod
metadata:
 name: annotations
 annotations:
  com.something.author: suhail
  com.course: DevOps
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80