apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    purpose: configuration
spec:
  containers:
    - name: config-pod
      image: nginx
      env:
      - name: COURSE
        valueFrom: 
          configMapKeyRef:
            name: config-map           # The ConfigMap this value comes from.
            key: COURSE
      - name: PERSON
        valueFrom: 
          configMapKeyRef:
            name: config-map          # The ConfigMap this value comes from.
            key: TRAINER 